Repository Alin0u/KI_Newsletter, pull requests merged in 2023-12, with the labels that each got.

#64 fix(authentication bug): fixed bug
  Backend/src/main/java/kgn/config/WebSecurityConfig.java
  Backend/src/main/java/kgn/dto/UserLoginDto.java
  Backend/src/test/java/kgn/AuthControllerTest.java
Labels: bug

#65 Feature/subject email
  Backend/src/main/java/kgn/service/NlpService.java
  Frontend/src/app/components/newsletter-creation/newsletter-creation.component.ts
  Frontend/src/app/services/text-processing.service.spec.ts
  Frontend/src/app/services/text-processing.service.ts
Labels: enhancement

#66 feat(settings): implemented settings and changed database
  Backend/src/main/java/kgn/config/WebSecurityConfig.java
  Backend/src/main/java/kgn/controller/ContactListController.java
  Backend/src/main/java/kgn/controller/HomeController.java
  Backend/src/main/java/kgn/controller/MailController.java
  Backend/src/main/java/kgn/dto/UserLoginDto.java
  Backend/src/main/java/kgn/dto/UserSettingsDto.java
  Backend/src/main/java/kgn/model/User.java
  Backend/src/main/java/kgn/service/FileService.java
  Backend/src/main/java/kgn/service/MailConfig.java
  Backend/src/main/java/kgn/service/MailProperties.java
  Backend/src/main/java/kgn/service/MailService.java
  Backend/src/main/java/kgn/service/NlpService.java
  Backend/src/main/java/kgn/service/SendGridService.java
  Backend/src/main/java/kgn/service/SettingsController.java
  Backend/src/main/resources/application-secure-sample.properties
  Backend/src/test/java/kgn/AuthControllerTest.java
  Backend/src/test/java/kgn/CustomUserDetailsServiceTest.java
  Frontend/src/app/app.module.ts
  Frontend/src/app/components/app-loading/app-loading.component.html
  Frontend/src/app/components/contact-list-dialog/contact-list-dialog.component.html
  Frontend/src/app/components/header/header.component.css
  Frontend/src/app/components/header/header.component.html
  Frontend/src/app/components/header/header.component.ts
  Frontend/src/app/components/newsletter-creation/newsletter-creation.component.css
  Frontend/src/app/components/newsletter-creation/newsletter-creation.component.ts
  Frontend/src/app/components/settings/settings.component.css
  Frontend/src/app/components/settings/settings.component.html
  Frontend/src/app/components/settings/settings.component.spec.ts
  Frontend/src/app/components/settings/settings.component.ts
  Frontend/src/app/components/settings/user-settings.model.ts
  Frontend/src/app/services/settings.service.spec.ts
  Frontend/src/app/services/settings.service.ts
  Frontend/src/assets/img/profile.svg
  INSTRUCTIONS.md
Labels: enhancement

#62 fix(Footer): fixed problem footer is not fixed at the bottom
  Frontend/src/app/app.component.html
  Frontend/src/app/components/footer/footer.component.css
  Frontend/src/app/components/newsletter-creation/newsletter-creation.component.css
  Frontend/src/styles.css
Labels: bug

#67 Feature/refactor
  Backend/src/main/java/kgn/config/WebSecurityConfig.java
  Backend/src/main/java/kgn/service/NlpService.java
  Backend/src/test/java/kgn/controller/MailControllerTest.java
  Frontend/src/app/app.component.ts
  Frontend/src/app/app.module.ts
  Frontend/src/app/components/app-loading/app-loading.component.html
  Frontend/src/app/components/contact-list-dialog/contact-list-dialog.component.html
  Frontend/src/app/components/contact-list-dialog/contact-list-dialog.component.ts
  Frontend/src/app/components/contactlist/contactlist.component.ts
  Frontend/src/app/components/header/header.component.html
  Frontend/src/app/components/header/header.component.ts
  Frontend/src/app/components/login/login.component.ts
  Frontend/src/app/components/newsletter-creation/newsletter-creation.component.html
  Frontend/src/app/components/newsletter-creation/newsletter-creation.component.ts
  Frontend/src/app/components/settings/settings.component.ts
  Frontend/src/app/services/auth.service.ts
  Frontend/src/app/services/contact-list.service.ts
  Frontend/src/app/services/mail.service.spec.ts
  Frontend/src/app/services/mail.service.ts
  Frontend/src/app/services/text-processing.service.ts
  Frontend/src/app/services/token.interceptor.ts
Labels: bug, enhancement
